"""
PDF export functionality for workspaces
"""

import io
import json
from datetime import datetime
from flask import jsonify, send_file
from .client import supabase
from .decorators import require_auth
from .utils import get_current_user_id
from .workspace_routes import workspace_bp

# WeasyPrint is optional - only needed for PDF export
try:
    from weasyprint import HTML
    WEASYPRINT_AVAILABLE = True
except (ImportError, OSError) as e:
    WEASYPRINT_AVAILABLE = False
    print(f"WARNING: WeasyPrint not available - PDF export will be disabled: {e}")
    print("         For local development, this is fine. For production, install GTK libraries.")


@workspace_bp.route('/<workspace_id>/export/pdf', methods=['GET'])
@require_auth
def export_workspace_pdf(workspace_id: str):
    """Export workspace as PDF"""
    # Check if WeasyPrint is available
    if not WEASYPRINT_AVAILABLE:
        return jsonify({
            "error": "PDF export is not available. WeasyPrint library is not installed.",
            "hint": "This feature requires GTK libraries. It may not work on Windows locally."
        }), 503

    try:
        user_id = get_current_user_id()

        # Get workspace
        workspace = supabase.table('workspaces') \
            .select('*') \
            .eq('id', workspace_id) \
            .eq('user_id', user_id) \
            .single() \
            .execute()

        if not workspace.data:
            return jsonify({"error": "Workspace not found"}), 404

        ws = workspace.data

        # Generate HTML for PDF
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    margin: 40px;
                }}
                h1 {{
                    color: #2563eb;
                    border-bottom: 3px solid #2563eb;
                    padding-bottom: 10px;
                }}
                h2 {{
                    color: #1e40af;
                    margin-top: 30px;
                }}
                .meta {{
                    color: #6b7280;
                    font-size: 14px;
                    margin-bottom: 20px;
                }}
                .qa-item {{
                    margin: 20px 0;
                    padding: 15px;
                    background: #f3f4f6;
                    border-left: 4px solid #2563eb;
                }}
                .question {{
                    font-weight: bold;
                    color: #1e40af;
                }}
                .answer {{
                    margin-top: 10px;
                }}
                .footer {{
                    margin-top: 50px;
                    text-align: center;
                    color: #6b7280;
                    font-size: 12px;
                }}
            </style>
        </head>
        <body>
            <h1>NormScout Compliance Report</h1>
            <div class="meta">
                <strong>Workspace:</strong> {ws['name']}<br>
                <strong>Generated:</strong> {datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}<br>
                <strong>Workspace #:</strong> {ws['workspace_number']}
            </div>

            <h2>Product Description</h2>
            <p>{ws['product_description']}</p>

            <h2>Compliance Results</h2>
            <p>{json.dumps(ws.get('matched_norms', []), indent=2)}</p>

            <h2>Question & Answer History</h2>
            {''.join([
                f'''
                <div class="qa-item">
                    <div class="question">Q: {qa['question']}</div>
                    <div class="answer">A: {qa['answer']}</div>
                </div>
                '''
                for qa in ws.get('qa_history', [])
            ]) or '<p>No questions asked yet.</p>'}

            <div class="footer">
                Generated by NormScout.ch
            </div>
        </body>
        </html>
        """

        # Convert to PDF
        if not WEASYPRINT_AVAILABLE:
            return jsonify({
                "error": "PDF export is not available in this environment. "
                        "WeasyPrint requires GTK libraries (Windows) or additional packages (Linux/Mac)."
            }), 503

        pdf = HTML(string=html_content).write_pdf()

        # Return as download
        return send_file(
            io.BytesIO(pdf),
            mimetype='application/pdf',
            as_attachment=True,
            download_name=f"{ws['name'].replace(' ', '_')}.pdf"
        )

    except Exception as e:
        return jsonify({"error": f"Export failed: {str(e)}"}), 500
